import { Skip } from "@/services/skip/skip.types";

export const mockSkips: Skip[] = [
  {
    id: "3",
    size: 4,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 100,
    vat: 100,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: true,
    allows_heavy_waste: false,
  },
  {
    id: "5",
    size: 8,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 120,
    vat: 120,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: true,
    allows_heavy_waste: false,
  },
  {
    id: "6",
    size: 10,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 150,
    vat: 150,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: true,
    allows_heavy_waste: false,
  },
  {
    id: "7",
    size: 12,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 211,
    vat: 211,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: false,
    allows_heavy_waste: false,
  },
  {
    id: "8",
    size: 14,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 250,
    vat: 250,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: false,
    allows_heavy_waste: false,
  },
  {
    id: "9",
    size: 16,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 368,
    vat: 368,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: false,
    allows_heavy_waste: false,
  },
  {
    id: "10",
    size: 40,
    hire_period_days: 14,
    transport_cost: null,
    per_tonne_cost: null,
    price_before_vat: 496,
    vat: 496,
    postcode: "",
    area: "",
    forbidden: false,
    created_at: "",
    updated_at: "",
    allowed_on_road: false,
    allows_heavy_waste: false,
  },
];
